### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by th3unkn0n** [sl4vkek/python-socialblade#1]
Require html parser or something ??

**Code :**
`#!/bin/env python3`
`from socialblade import YouTubeChannel`
`channel = YouTubeChannel('UC-lHJZR3Gqxm24_Vd_AJ5Yw')`
`print(channel.get_subscriber_count())`

**Output :**
`Traceback (most recent call last):`
 ` File "sub.py", line 5, in <module>`
  `  print(channel.get_subscriber_count())`
`  File "/usr/local/lib/python3.7/dist-packages/socialblade/__init__.py", line 132, in get_subscriber_count`
 `   'query': self.channel_id`
`ValueError: invalid literal for int() with base 10: '<!DOCTYPE html>\n<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en-US"> <![endif]-->\n<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en-US"> <![endif]-->\n<!--[if IE 8]>    <html class=`

**Comment by SirRobo** [comment]
Hello th3! 

I am not affiliated with this project, I just wanted to let you know I'm pretty sure it's a problem on SocialBlades side. It returns HTML that is a cloudflare template that says "Please enable cookies"
