### ISSUE TITLE
Seeing stats overtime?

### ISSUE THREAD

**Issue by rachelombok** [sl4vkek/python-socialblade#12]
I think this is more of a feature request than an issue, but is there any way to see subscribers/followers over time, like how the graphs/charts show them on social blade? Like for example getting the subscribers of a channel from each month for the last two years? I was curious to ask because I know you can get live updates I was wondering if you could access historical data as well. Thanks!

**Comment by meatyite** [comment]
i really dont know how to implement that, the way socialblade works. i think that would require scraping rather than API stuff

**Comment by meatyite** [comment]
you can feel free to experiment and post a pull request though
