### ISSUE TITLE
sub count issue

### ISSUE THREAD

**Issue by aggbhh** [sl4vkek/python-socialblade#2]
When i use the code provided in README.md and run it, the shell kinda becames a notepad.

its like this:

Python 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 22:45:29) [MSC v.1916 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
= RESTART: C:/Users/agg20/AppData/Local/Programs/Python/Python38-32/pewdssubtest.py
(you can write anything here)

**Comment by meatyite** [comment]
Hi, sorry for answering late i dont check my github that often.
I need some more details. what command did you write in cmd/powershell? did you copy the example 1:1 or did you change some stuff? can you give the entire code? does it write the CSV or not?

**Comment by meatyite** [comment]
This is fixed in the new 1.0.2 update. Closed
