### ISSUE TITLE
Cloudflare now blocks API access to socialblade.

### ISSUE THREAD

**Issue by meatyite** [sl4vkek/python-socialblade#3]
This package wont work until socialblade decides to stop using cloudflare.
I can't fix this issue, i'm sorry but this package will not work anymore.

**Comment by FredHags** [comment]
Hi,

replace the "requests" with "cloudscraper" and it will work again.
also "self.__s = requests.Session()" will be "self.__s = cloudscraper.create_scraper()"

**Comment by meatyite** [comment]
> 
> 
> Hi,
> 
> replace the "requests" with "cloudscraper" and it will work again.
> also "self.__s = requests.Session()" will be "self.__s = cloudscraper.create_scraper()"

oh my god i've been searching for something like this for ages. Thanks!
The latest commit now implemented this and its fixed.
