### ISSUE TITLE
Add examples and documentation for the new Twitch and StoryFire support

### ISSUE THREAD

**Issue by meatyite** [sl4vkek/python-socialblade#5]
@SuperSonicHub1 You said wanted to do that right? well this is your task now

**Comment by meatyite** [comment]
You can write the examples in README.md, just use a Markdown to reStructuredText converter for the README.rst (i need the .rst because PyPi doesn't accept .md)

**Comment by SuperSonicHub1** [comment]
Sweet! I'm glad my changes were accepted! I'll be submitting a pull request
by the end of the day.

Kyle Williams

**Comment by SuperSonicHub1** [comment]
#6 
Did it. Take a look.

**Comment by meatyite** [comment]
Pull request merged. Thanks
